/**
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.example.mydsl.vaselina.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.vaselina.VaselinaPackage;
import org.xtext.example.mydsl.vaselina.arrayDimension;
import org.xtext.example.mydsl.vaselina.arrayRefs;
import org.xtext.example.mydsl.vaselina.varSymbol;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>array Refs</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.vaselina.impl.arrayRefsImpl#getArrRefs <em>Arr Refs</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.vaselina.impl.arrayRefsImpl#getDims <em>Dims</em>}</li>
 * </ul>
 *
 * @generated
 */
public class arrayRefsImpl extends VariableImpl implements arrayRefs
{
  /**
   * The cached value of the '{@link #getArrRefs() <em>Arr Refs</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArrRefs()
   * @generated
   * @ordered
   */
  protected varSymbol arrRefs;

  /**
   * The cached value of the '{@link #getDims() <em>Dims</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDims()
   * @generated
   * @ordered
   */
  protected EList<arrayDimension> dims;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected arrayRefsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VaselinaPackage.Literals.ARRAY_REFS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public varSymbol getArrRefs()
  {
    if (arrRefs != null && arrRefs.eIsProxy())
    {
      InternalEObject oldArrRefs = (InternalEObject)arrRefs;
      arrRefs = (varSymbol)eResolveProxy(oldArrRefs);
      if (arrRefs != oldArrRefs)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, VaselinaPackage.ARRAY_REFS__ARR_REFS, oldArrRefs, arrRefs));
      }
    }
    return arrRefs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public varSymbol basicGetArrRefs()
  {
    return arrRefs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setArrRefs(varSymbol newArrRefs)
  {
    varSymbol oldArrRefs = arrRefs;
    arrRefs = newArrRefs;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VaselinaPackage.ARRAY_REFS__ARR_REFS, oldArrRefs, arrRefs));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<arrayDimension> getDims()
  {
    if (dims == null)
    {
      dims = new EObjectContainmentEList<arrayDimension>(arrayDimension.class, this, VaselinaPackage.ARRAY_REFS__DIMS);
    }
    return dims;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case VaselinaPackage.ARRAY_REFS__DIMS:
        return ((InternalEList<?>)getDims()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VaselinaPackage.ARRAY_REFS__ARR_REFS:
        if (resolve) return getArrRefs();
        return basicGetArrRefs();
      case VaselinaPackage.ARRAY_REFS__DIMS:
        return getDims();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VaselinaPackage.ARRAY_REFS__ARR_REFS:
        setArrRefs((varSymbol)newValue);
        return;
      case VaselinaPackage.ARRAY_REFS__DIMS:
        getDims().clear();
        getDims().addAll((Collection<? extends arrayDimension>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VaselinaPackage.ARRAY_REFS__ARR_REFS:
        setArrRefs((varSymbol)null);
        return;
      case VaselinaPackage.ARRAY_REFS__DIMS:
        getDims().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VaselinaPackage.ARRAY_REFS__ARR_REFS:
        return arrRefs != null;
      case VaselinaPackage.ARRAY_REFS__DIMS:
        return dims != null && !dims.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //arrayRefsImpl
