/**
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.example.mydsl.vaselina.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.vaselina.FuncParameter;
import org.xtext.example.mydsl.vaselina.VaselinaPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Func Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FuncParameterImpl extends varSymbolImpl implements FuncParameter
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FuncParameterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VaselinaPackage.Literals.FUNC_PARAMETER;
  }

} //FuncParameterImpl
