/**
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.example.mydsl.vaselina.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.vaselina.VaselinaPackage;
import org.xtext.example.mydsl.vaselina.varRefs;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>var Refs</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class varRefsImpl extends VariableImpl implements varRefs
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected varRefsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VaselinaPackage.Literals.VAR_REFS;
  }

} //varRefsImpl
