/**
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.example.mydsl.vaselina.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.vaselina.FuncDefinition;
import org.xtext.example.mydsl.vaselina.VaselinaPackage;
import org.xtext.example.mydsl.vaselina.VaselinaProgram;
import org.xtext.example.mydsl.vaselina.mainDeclared;
import org.xtext.example.mydsl.vaselina.varDeclared;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.vaselina.impl.VaselinaProgramImpl#getGlobal <em>Global</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.vaselina.impl.VaselinaProgramImpl#getFunc <em>Func</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.vaselina.impl.VaselinaProgramImpl#getMain <em>Main</em>}</li>
 * </ul>
 *
 * @generated
 */
public class VaselinaProgramImpl extends MinimalEObjectImpl.Container implements VaselinaProgram
{
  /**
   * The cached value of the '{@link #getGlobal() <em>Global</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGlobal()
   * @generated
   * @ordered
   */
  protected EList<varDeclared> global;

  /**
   * The cached value of the '{@link #getFunc() <em>Func</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFunc()
   * @generated
   * @ordered
   */
  protected EList<FuncDefinition> func;

  /**
   * The cached value of the '{@link #getMain() <em>Main</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMain()
   * @generated
   * @ordered
   */
  protected mainDeclared main;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VaselinaProgramImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VaselinaPackage.Literals.VASELINA_PROGRAM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<varDeclared> getGlobal()
  {
    if (global == null)
    {
      global = new EObjectContainmentEList<varDeclared>(varDeclared.class, this, VaselinaPackage.VASELINA_PROGRAM__GLOBAL);
    }
    return global;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<FuncDefinition> getFunc()
  {
    if (func == null)
    {
      func = new EObjectContainmentEList<FuncDefinition>(FuncDefinition.class, this, VaselinaPackage.VASELINA_PROGRAM__FUNC);
    }
    return func;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public mainDeclared getMain()
  {
    return main;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMain(mainDeclared newMain, NotificationChain msgs)
  {
    mainDeclared oldMain = main;
    main = newMain;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, VaselinaPackage.VASELINA_PROGRAM__MAIN, oldMain, newMain);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMain(mainDeclared newMain)
  {
    if (newMain != main)
    {
      NotificationChain msgs = null;
      if (main != null)
        msgs = ((InternalEObject)main).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - VaselinaPackage.VASELINA_PROGRAM__MAIN, null, msgs);
      if (newMain != null)
        msgs = ((InternalEObject)newMain).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - VaselinaPackage.VASELINA_PROGRAM__MAIN, null, msgs);
      msgs = basicSetMain(newMain, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VaselinaPackage.VASELINA_PROGRAM__MAIN, newMain, newMain));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case VaselinaPackage.VASELINA_PROGRAM__GLOBAL:
        return ((InternalEList<?>)getGlobal()).basicRemove(otherEnd, msgs);
      case VaselinaPackage.VASELINA_PROGRAM__FUNC:
        return ((InternalEList<?>)getFunc()).basicRemove(otherEnd, msgs);
      case VaselinaPackage.VASELINA_PROGRAM__MAIN:
        return basicSetMain(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VaselinaPackage.VASELINA_PROGRAM__GLOBAL:
        return getGlobal();
      case VaselinaPackage.VASELINA_PROGRAM__FUNC:
        return getFunc();
      case VaselinaPackage.VASELINA_PROGRAM__MAIN:
        return getMain();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VaselinaPackage.VASELINA_PROGRAM__GLOBAL:
        getGlobal().clear();
        getGlobal().addAll((Collection<? extends varDeclared>)newValue);
        return;
      case VaselinaPackage.VASELINA_PROGRAM__FUNC:
        getFunc().clear();
        getFunc().addAll((Collection<? extends FuncDefinition>)newValue);
        return;
      case VaselinaPackage.VASELINA_PROGRAM__MAIN:
        setMain((mainDeclared)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VaselinaPackage.VASELINA_PROGRAM__GLOBAL:
        getGlobal().clear();
        return;
      case VaselinaPackage.VASELINA_PROGRAM__FUNC:
        getFunc().clear();
        return;
      case VaselinaPackage.VASELINA_PROGRAM__MAIN:
        setMain((mainDeclared)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VaselinaPackage.VASELINA_PROGRAM__GLOBAL:
        return global != null && !global.isEmpty();
      case VaselinaPackage.VASELINA_PROGRAM__FUNC:
        return func != null && !func.isEmpty();
      case VaselinaPackage.VASELINA_PROGRAM__MAIN:
        return main != null;
    }
    return super.eIsSet(featureID);
  }

} //VaselinaProgramImpl
