/*
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.Vaselina.ui.internal.VaselinaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VaselinaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(VaselinaActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		VaselinaActivator activator = VaselinaActivator.getInstance();
		return activator != null ? activator.getInjector(VaselinaActivator.ORG_XTEXT_EXAMPLE_MYDSL_VASELINA) : null;
	}

}
