/**
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.example.mydsl.vaselina;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>array Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.vaselina.arrayRef#getVarRef <em>Var Ref</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.vaselina.arrayRef#getDim <em>Dim</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getarrayRef()
 * @model
 * @generated
 */
public interface arrayRef extends varExpression
{
  /**
   * Returns the value of the '<em><b>Var Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Ref</em>' reference.
   * @see #setVarRef(varSymbol)
   * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getarrayRef_VarRef()
   * @model
   * @generated
   */
  varSymbol getVarRef();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.vaselina.arrayRef#getVarRef <em>Var Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Ref</em>' reference.
   * @see #getVarRef()
   * @generated
   */
  void setVarRef(varSymbol value);

  /**
   * Returns the value of the '<em><b>Dim</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.vaselina.arrayDimension}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dim</em>' containment reference list.
   * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getarrayRef_Dim()
   * @model containment="true"
   * @generated
   */
  EList<arrayDimension> getDim();

} // arrayRef
