/**
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.example.mydsl.vaselina;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>array Dimension</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.vaselina.arrayDimension#getIndex <em>Index</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.vaselina.arrayDimension#getSize <em>Size</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getarrayDimension()
 * @model
 * @generated
 */
public interface arrayDimension extends EObject
{
  /**
   * Returns the value of the '<em><b>Index</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Index</em>' reference.
   * @see #setIndex(varSymbol)
   * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getarrayDimension_Index()
   * @model
   * @generated
   */
  varSymbol getIndex();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.vaselina.arrayDimension#getIndex <em>Index</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Index</em>' reference.
   * @see #getIndex()
   * @generated
   */
  void setIndex(varSymbol value);

  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see #setSize(int)
   * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getarrayDimension_Size()
   * @model
   * @generated
   */
  int getSize();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.vaselina.arrayDimension#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see #getSize()
   * @generated
   */
  void setSize(int value);

} // arrayDimension
