/**
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.example.mydsl.vaselina;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Brk Str</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.vaselina.BrkStr#getBrk <em>Brk</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getBrkStr()
 * @model
 * @generated
 */
public interface BrkStr extends BodyStatement
{
  /**
   * Returns the value of the '<em><b>Brk</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Brk</em>' attribute.
   * @see #setBrk(String)
   * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getBrkStr_Brk()
   * @model
   * @generated
   */
  String getBrk();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.vaselina.BrkStr#getBrk <em>Brk</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Brk</em>' attribute.
   * @see #getBrk()
   * @generated
   */
  void setBrk(String value);

} // BrkStr
