/**
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.example.mydsl.vaselina;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Func Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getFuncParameter()
 * @model
 * @generated
 */
public interface FuncParameter extends varSymbol
{
} // FuncParameter
