/**
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.example.mydsl.vaselina;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Plus Or Minus</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.vaselina.PlusOrMinus#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.vaselina.PlusOrMinus#getOp <em>Op</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.vaselina.PlusOrMinus#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getPlusOrMinus()
 * @model
 * @generated
 */
public interface PlusOrMinus extends varExpression
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(varExpression)
   * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getPlusOrMinus_Left()
   * @model containment="true"
   * @generated
   */
  varExpression getLeft();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.vaselina.PlusOrMinus#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(varExpression value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getPlusOrMinus_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.vaselina.PlusOrMinus#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(varExpression)
   * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getPlusOrMinus_Right()
   * @model containment="true"
   * @generated
   */
  varExpression getRight();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.vaselina.PlusOrMinus#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(varExpression value);

} // PlusOrMinus
