/**
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.example.mydsl.vaselina;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Return Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.vaselina.ReturnDeclaration#getRtnType <em>Rtn Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getReturnDeclaration()
 * @model
 * @generated
 */
public interface ReturnDeclaration extends BodyStatement
{
  /**
   * Returns the value of the '<em><b>Rtn Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rtn Type</em>' attribute.
   * @see #setRtnType(String)
   * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getReturnDeclaration_RtnType()
   * @model
   * @generated
   */
  String getRtnType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.vaselina.ReturnDeclaration#getRtnType <em>Rtn Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rtn Type</em>' attribute.
   * @see #getRtnType()
   * @generated
   */
  void setRtnType(String value);

} // ReturnDeclaration
