/**
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.example.mydsl.vaselina;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>var Refs</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getvarRefs()
 * @model
 * @generated
 */
public interface varRefs extends Variable
{
} // varRefs
