/**
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.example.mydsl.vaselina;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>var Return</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.vaselina.varReturn#getRtn <em>Rtn</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getvarReturn()
 * @model
 * @generated
 */
public interface varReturn extends BodyStatement
{
  /**
   * Returns the value of the '<em><b>Rtn</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rtn</em>' containment reference.
   * @see #setRtn(varExpression)
   * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getvarReturn_Rtn()
   * @model containment="true"
   * @generated
   */
  varExpression getRtn();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.vaselina.varReturn#getRtn <em>Rtn</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rtn</em>' containment reference.
   * @see #getRtn()
   * @generated
   */
  void setRtn(varExpression value);

} // varReturn
