/**
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.example.mydsl.vaselina;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.vaselina.VaselinaProgram#getGlobal <em>Global</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.vaselina.VaselinaProgram#getFunc <em>Func</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.vaselina.VaselinaProgram#getMain <em>Main</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getVaselinaProgram()
 * @model
 * @generated
 */
public interface VaselinaProgram extends EObject
{
  /**
   * Returns the value of the '<em><b>Global</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.vaselina.varDeclared}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Global</em>' containment reference list.
   * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getVaselinaProgram_Global()
   * @model containment="true"
   * @generated
   */
  EList<varDeclared> getGlobal();

  /**
   * Returns the value of the '<em><b>Func</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.vaselina.FuncDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Func</em>' containment reference list.
   * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getVaselinaProgram_Func()
   * @model containment="true"
   * @generated
   */
  EList<FuncDefinition> getFunc();

  /**
   * Returns the value of the '<em><b>Main</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Main</em>' containment reference.
   * @see #setMain(mainDeclared)
   * @see org.xtext.example.mydsl.vaselina.VaselinaPackage#getVaselinaProgram_Main()
   * @model containment="true"
   * @generated
   */
  mainDeclared getMain();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.vaselina.VaselinaProgram#getMain <em>Main</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Main</em>' containment reference.
   * @see #getMain()
   * @generated
   */
  void setMain(mainDeclared value);

} // VaselinaProgram
