/*
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalVaselinaParser;
import org.xtext.example.mydsl.services.VaselinaGrammarAccess;

public class VaselinaParser extends AbstractAntlrParser {

	@Inject
	private VaselinaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalVaselinaParser createParser(XtextTokenStream stream) {
		return new InternalVaselinaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "VaselinaProgram";
	}

	public VaselinaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(VaselinaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
