/*
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.example.mydsl.ide;


/**
 * Use this class to register ide components.
 */
public class VaselinaIdeModule extends AbstractVaselinaIdeModule {
}
