/*
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.VaselinaRuntimeModule;
import org.xtext.example.mydsl.VaselinaStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class VaselinaIdeSetup extends VaselinaStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new VaselinaRuntimeModule(), new VaselinaIdeModule()));
	}
	
}
