/*
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class VaselinaUiModule extends AbstractVaselinaUiModule {

	public VaselinaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
